export const UPDATE_CODE_INPUT = 'UPDATE_CODE_INPUT';
export const UPDATE_CODE_EDITOR_INPUT = 'UPDATE_CODE_EDITOR_INPUT'
export const SET_DATABASE_REQUESTS = 'SET_DATABASE_REQUESTS';
export const SET_DATA_POINTS = 'SET_DATA_POINTS';
export const SET_NESTING_DEPTH = "SET_NESTING_DEPTH";
export const SET_NETWORK_LATENCY = "SET_NETWORK_LATENCY";
export const SET_EFFECTIVE_RUNTIME = "SET_EFFECTIVE_RUNTIME";

